name: free_2_play
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.6
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  persistent_bottom_nav_bar_v2: ^5.2.3
  get: ^4.6.6
  flutter_gemini: ^2.0.3
  image_picker: ^1.1.1
  dash_chat_2: ^0.0.20
  flutter_markdown: 0.6.23
  flutter_inset_box_shadow: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logos/
  fonts:
    - family: "Motiva Sans"
      fonts:
        - asset: assets/fonts/MotivaSansRegular.woff.ttf
        - asset: assets/fonts/MotivaSansBold.woff.ttf
          weight: 700
    - family: Arial
      fonts:
        - asset: assets/fonts/ARIAL.ttf
    # - family: Arial
    #   fonts:
    #     - asset: assets/fonts/ARIAL.TTF

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/logos/logo_icon.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   web:
#     generate: true
#     image_path: "assets/logos/logo_icon.png"
#     background_color: "#FFFFFF"
#     theme_color: "#FFFFFF"
#   windows:
#     generate: true
#     image_path: "assets/logos/logo_icon.png"
#     icon_size: 256 # min:48, max:256, default: 48

#   macos:
#     generate: true
#     image_path: "assets/logos/logo_icon.png"
